export const AllDesks: Desk[] = [
  { id: 1, type: "individual", membership: "basic", booked: false },
  { id: 2, type: "individual", membership: "premium", booked: false },
  { id: 3, type: "individual", membership: "executive", booked: false },
  { id: 4, type: "individual", membership: "executive", booked: false },
  { id: 5, type: "individual", membership: "executive", booked: false },
  { id: 6, type: "individual", membership: "executive", booked: false },
  { id: 7, type: "individual", membership: "executive", booked: false },
  { id: 8, type: "individual", membership: "executive", booked: false },
  { id: 9, type: "individual", membership: "executive", booked: false },
  { id: 10, type: "individual", membership: "executive", booked: false },
  { id: 11, type: "team", booked: false },
  { id: 12, type: "team", booked: false },
  { id: 13, type: "team", booked: false },
  { id: 14, type: "team", booked: false },
  { id: 15, type: "team", booked: false },
];
